<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>default</LangVersion>
    <TargetFramework>net4.8</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>Debug;Release</Configurations>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\DLL\publicized_assemblies\Assembly-CSharp_publicized.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\..\DLL\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="LabApi">
      <HintPath>..\..\..\DLL\LabApi.dll</HintPath>
    </Reference>
    <Reference Include="mscorlib">
      <HintPath>..\..\..\DLL\mscorlib.dll</HintPath>
    </Reference>
    <Reference Include="System">
      <HintPath>..\..\..\DLL\System.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\DLL\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectMER\ProjectMER.csproj" />
  </ItemGroup>

</Project>
