namespace ProjectMER.Features.Enums;

public enum ExtendedRoomName
{
    Unnamed,
    LczClassDSpawn,
    LczComputerRoom,
    LczCheckpointA,
    LczCheckpointB,
    LczToilets,
    LczArmory,
    Lcz173,
    LczGlassroom,
    Lcz330,
    Lcz914,
    LczGreenhouse,
    LczAirlock,
    HczCheckpointToEntranceZone,
    HczCheckpointA,
    HczCheckpointB,
    HczWarhead,
    Hcz049,
    Hcz079,
    Hcz096,
    Hcz106,
    Hcz939,
    HczMicroHID,
    HczArmory,
    HczServers,
    HczTesla,
    EzCollapsedTunnel,
    EzGateA,
    EzGateB,
    EzRedroom,
    EzEvacShelter,
    EzIntercom,
    EzOfficeStoried,
    EzOfficeLarge,
    EzOfficeSmall,
    Outside,
    Pocket,
    HczTestroom,
    Hcz127,
    HczAcroamaticAbatement,
    HczWaysideIncinerator,
    HczRampTunnel,
    
    // custom
    HczCornerDeep = 247,
    EzCafeteria = 248,
    EzChef = 249,
    EzSmallRooms1 = 250,
    EzSmallRooms2 = 251,
    EzStraightColumn = 252,
    HczIntersectionJunk = 253,
    HczStraightC = 254,
    HczStraightPipeRoom = 255,
}